{
 "title": "Detailed Kapline",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Richieste analizzate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "predictedLabel.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "20m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Score ottenuti in base alle dimensioni",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "size", "id": "1", "type": "avg" },
      { "field": "max_score", "id": "3", "type": "avg" },
      { "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Azioni", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Azioni eseguite",
   "type": "barchart",
   "description": "Descrive le label in base alla classificazione sulle regole di quark-engine",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Score medio sulle azioni",
   "type": "bargauge",
   "description": "Le azioni sono insiemi di regole che mirano a classificare il comportamento di un'applicazione.",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Dimensioni", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Riepilogo Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Media e somma della dimensioni",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "predictedLabel.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "size",
       "id": "3",
       "meta": {
        "avg": true,
        "count": false,
        "max": true,
        "min": true,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false,
        "sum": true
       },
       "type": "extended_stats"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Dimensione media nel tempo",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "predictedLabel.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "size", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}