{
 "title": "Kapline",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Richieste analizzate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "predictedLabel.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "20m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "File analizzati",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "predictedLabel.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Azioni eseguite",
   "type": "barchart",
   "description": "Descrive le label in base alla classificazione sulle regole di quark-engine",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bytes totali analizzati",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Dimensioni",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "predictedLabel.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "size", "id": "1", "type": "avg" },
      {
       "field": "size",
       "id": "3",
       "meta": {
        "count": false,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false,
        "sum": true
       },
       "type": "extended_stats"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}